Deprecate kyma provision k3d command
kyma-project/api-gateway pull request #1037
Opened 2024-05-06 11:22 UTC by halamix2

**Description**

Changes proposed in this pull request:

- Deprecate kyma provision k3d command

**Related issues**

- https://github.com/kyma-project/kyma/issues/18652

2024-05-06 11:22 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/api-gateway?pullRequest=1037) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/api-gateway?pullRequest=1037) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/api-gateway?pullRequest=1037) it.</sub>

2024-05-08 09:06 UTC, IwonaLanger submitted a review, later dismissed

2024-05-08 09:09 UTC, barchw requested changes

2024-05-08 09:09 UTC, barchw commented on docs/contributor/01-00-installation.md
> +    k3d cluster create kyma --kubeconfig-switch-context -p 80:80@loadbalancer -p 443:443@loadbalancer --registry-use kyma-registry
```suggestion
    k3d cluster create kyma --kubeconfig-switch-context -p 80:80@loadbalancer -p 443:443@loadbalancer --registry-use kyma-registry --k3s-arg "--disable=traefik@server:0"
```

2024-05-08 09:10 UTC, barchw requested changes

2024-05-08 09:10 UTC, barchw commented on tests/ui/tests/scripts/k3d-local-dev.sh
> +k3d cluster create
```suggestion
k3d cluster create --port 80:80@loadbalancer --port 443:443@loadbalancer --k3s-arg "--disable=traefik@server:0"
```

2024-05-08 09:26 UTC, barchw approved these changes

2024-05-08 09:28 UTC, IwonaLanger approved these changes

2024-05-08 09:55 UTC, merged