Add Pre-Merge Checklist to the PR template
kyma-project/api-gateway pull request #1136
Opened 2024-06-28 11:52 UTC by kolodziejczak

**Description**

Changes proposed in this pull request:

- Add Pre-Merge Checklist to the PR template

2024-06-28 11:54 UTC, barchw requested changes

2024-06-28 11:54 UTC, barchw commented on .github/pull-request-template.md
> +Pre-Merge Checklist:
```suggestion
**Pre-Merge Checklist**
```

2024-06-28 12:27 UTC, barchw approved these changes

2024-07-01 06:00 UTC, nataliasitko approved these changes

2024-07-01 06:01 UTC, merged