Add FQDN in CEL validation
kyma-project/api-gateway pull request #1210
Opened 2024-07-31 07:36 UTC by werdes72

**Description**

Changes proposed in this pull request:

- Use CEL validation for FQDN hosts
- Fix Docker warning

**Pre-Merge Checklist**

- [ ] As a PR reviewer, verify code coverage and evaluate if it is acceptable.

**Related issues**
#1149

2024-08-02 09:16 UTC, barchw requested changes

2024-08-02 09:16 UTC, barchw commented on controllers/gateway/api_controller_integration_test.go
> +		It("should not create an APIRule with host name without domain", func() {
There's a lot of stuff duplicated in those tests, maybe we could make them into a table, or at least create some setup func that would take just the host?

2024-08-02 12:37 UTC, barchw requested changes
Needs docs, otherwise LGTM

2024-08-02 12:53 UTC, barchw submitted a review, later dismissed

2024-08-02 13:07 UTC, nataliasitko commented on docs/user/custom-resources/apirule/v2alpha1/04-10-apirule-custom-resource.md
> +| **gateway**                                      | **YES**  | Specifies the Istio Gateway it must reference actual gateway on the cluster.
```suggestion
| **gateway**                                      | **YES**  | Specifies the Istio Gateway. The value must reference an actual Gateway in the cluster.                                                                                                                                                                                                          | It must be in the `namespace/gateway` format. The namespace and the Gateway cannot be longer than 63 characters each. |
```

2024-08-02 13:13 UTC, nataliasitko commented on docs/release-notes/2.5.0.md
> +- Add gateway validation [#1210](https://github.com/kyma-project/api-gateway/pull/1210)
```suggestion
- Add Gateway validation [#1210](https://github.com/kyma-project/api-gateway/pull/1210)
```

2024-08-05 06:40 UTC, nataliasitko approved these changes

2024-08-05 06:42 UTC, merged