Better empty spec error message
kyma-project/api-gateway pull request #1263
Opened 2024-08-20 13:15 UTC by videlov

**Description**

Changes proposed in this pull request:

- Better empty spec error message

**Pre-Merge Checklist**

- [ ] As a PR reviewer, verify code coverage and evaluate if it is acceptable.

**Related issues**

2024-08-20 13:16 UTC, nataliasitko approved these changes

2024-08-20 13:21 UTC, barchw requested changes

2024-08-20 13:30 UTC, videlov commented on internal/validation/v2alpha1/v2alpha1.go
> +			Message:       "APIRule in version v2alpha1 contains an empty spec. To troubleshoot, see https://kyma-project.io/#/api-gateway/user/troubleshooting-guides/03-70-empty-apirule-spec.",
yes, this is quite in the grayish area of nice, I would also avoid it. we just try to be a bit more helpful if someone is actually checking error state messages. configurable is a bit too much, will move it to a constant.

2024-08-20 14:45 UTC, videlov commented on internal/validation/v2alpha1/v2alpha1.go
> +			Message:       "APIRule in version v2alpha1 contains an empty spec. To troubleshoot, see https://kyma-project.io/#/api-gateway/user/troubleshooting-guides/03-70-empty-apirule-spec.",
@nataliasitko any input on this? how can we ensure link is still valid and not outdated, what is best practice?

2024-08-21 08:43 UTC, nataliasitko commented on internal/validation/v2alpha1/v2alpha1.go
> +			Message:       "APIRule in version v2alpha1 contains an empty spec. To troubleshoot, see https://kyma-project.io/#/api-gateway/user/troubleshooting-guides/03-70-empty-apirule-spec.",
I agree with you. I didn't think about the fact that when a link breaks, we won't spot it. I asked other TWs how they handle links in error messages, as I'm not aware of any tool to check this

2024-08-22 07:28 UTC, nataliasitko commented on internal/validation/v2alpha1/v2alpha1.go
> +			Message:       "APIRule in version v2alpha1 contains an empty spec. To troubleshoot, see https://kyma-project.io/#/api-gateway/user/troubleshooting-guides/03-70-empty-apirule-spec.",
I learned that [Huskies also add links to error messages](https://github.com/kyma-project/telemetry-manager/blob/424444fb73c5b22507e47e3b1db53d60b53d18b8/internal/conditions/conditions.go#L74). Some teams have custom link checks in their repos (besides the general [md-link-check](https://github.com/kyma-project/md-check-link/actions)) but I'm not sure if they also check non-md files
Alternatively, maybe we could link to the troubleshooting folder? It's very unlikely this link will get broken: https://kyma-project.io/#/api-gateway/user/troubleshooting-guides/README

2024-08-22 07:31 UTC, barchw commented on internal/validation/v2alpha1/v2alpha1.go
> +			Message:       "APIRule in version v2alpha1 contains an empty spec. To troubleshoot, see https://kyma-project.io/#/api-gateway/user/troubleshooting-guides/03-70-empty-apirule-spec.",
I guess we can add that, and we could have some backlog item to add a linter that would check for deadlinks
Running a simple regex search for `kyma-project.io` links and then checking if something is behind them should be fairly easy.

2024-08-22 07:32 UTC, barchw approved these changes

2024-08-27 08:53 UTC, nataliasitko approved these changes

2024-08-27 10:57 UTC, barchw commented
/recheck-cla

2024-08-27 12:52 UTC, barchw approved these changes

2024-08-28 13:05 UTC, videlov commented
/retest

2024-08-28 15:23 UTC, barchw approved these changes

2024-08-29 08:31 UTC, nataliasitko approved these changes

2024-08-29 08:32 UTC, merged