APIRule v2alpha1 UI
kyma-project/api-gateway pull request #1374
Opened 2024-10-11 11:29 UTC by triffer

**Description**

Changes proposed in this pull request:

- Add UI for APIRule v2alpha1
- Exclude v2alpha1 APIRules from existing v1beta1 UI

**Pre-Merge Checklist**

- [ ] As a PR reviewer, verify code coverage and evaluate if it is acceptable.

**Related issues**

- https://github.com/kyma-project/api-gateway/issues/1353

2024-10-15 10:10 UTC, triffer commented on config/ui-extensions/apirules-v2alpha1/translations
> +  alert.spec.host: Host can not be a wildcard, replace with a RFC 1123 label or a valid, fully qualified domain name (FQDN)
This is not used in v2alpha1 and we can remove it.

2024-10-17 13:07 UTC, barchw requested changes
This actually looks much better than the v1beta1 UI, looks like having the accessStrategies as separate subfields was a good idea 😄 

Only question I have is to the behaviour of the `noAuth` boolean: looks like you have to click the switch to set up noAuth, even though you have already selected accessStrategy `noAuth`.

2024-10-18 13:06 UTC, barchw approved these changes

2024-10-21 07:19 UTC, nataliasitko approved these changes

2024-10-21 07:29 UTC, merged