bug: RateLimit: replace Watch with polling
kyma-project/api-gateway pull request #1558
Opened 2024-12-23 09:14 UTC by Ressetkk

/kind bug
/area api-gateway

* Requeue reconciliation every 3 minutes, accepting downtime
* Add warning state to the CR status
* Adjust tests

Restore watching should be handled in a follow-up anytime soon.

#1516

2024-12-23 14:32 UTC, videlov submitted a review, later dismissed

2024-12-23 14:33 UTC, barchw requested changes

2024-12-23 14:33 UTC, barchw commented on main.go
> +	if err = ratelimit.Setup(mgr, 3*time.Minute, scheme); err != nil {
Please make that a configurable parameter / flag / const

2024-12-23 14:57 UTC, barchw approved these changes
<img width="943" alt="Screenshot 2024-12-23 at 15 56 43" src="https://github.com/user-attachments/assets/b9e1ee4d-f0af-4497-befe-f051211bd129" />
Looks much better, TY
Don't know if it should be an `Error` though? From the Kyma Module api standpoint it's more in the `warning`, user action territory

2024-12-24 07:44 UTC, mluk-sap approved these changes

2024-12-24 12:02 UTC, merged