Add optional `namespace` for `service` in APIRule
kyma-project/api-gateway pull request #29
Opened 2022-09-19 07:45 UTC by videlov

**Description**

Added optional `namespace` in `service` for APIRule CRD (on root `spec` or as subelement in `rules`)

Changes in this pull request:

- [/] Update API-Rule CRD
- [/] Adapt target for ory-proxy Ory Rule and upstream for VirtualService
- [ ] API exposure tutorials updated
- [ ] APIRule CR documentation updated
- [ ] api-gateway tests updated

**Related issue(s)**
https://github.com/kyma-project/kyma/issues/9936

2022-09-19 07:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/api-gateway?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/api-gateway?pullRequest=29) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/api-gateway?pullRequest=29) it.</sub>

2022-09-19 07:45 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/kyma-project/api-gateway?pullRequest=29) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/kyma-project/api-gateway?pullRequest=29) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/kyma-project/api-gateway?pullRequest=29) it.</sub>

2022-09-23 12:37 UTC, werdes72 approved these changes

2022-09-27 11:50 UTC, barchw requested changes
Could you please format with `gofmt -s -w .`?

2022-09-27 11:57 UTC, videlov commented
> gofmt -s -w .

done

2022-09-27 12:23 UTC, barchw requested changes

2022-09-27 12:23 UTC, barchw commented on internal/processing/processing_test.go
> +			It("should override upstream for specified spec level service namespace", func() {
```suggestion
			It("should override VS destination host for specified spec level service namespace", func() {
```

2022-09-27 12:23 UTC, barchw commented on internal/processing/processing_test.go
> +				//Verify AR has rule level upstream
```suggestion
				//Verify AR does not exist
```

2022-09-27 12:23 UTC, barchw commented on internal/processing/processing_test.go
> +				//Verify AR has rule level upstream
```suggestion
				//Verify AR does not exist
```

2022-09-27 12:23 UTC, barchw commented on internal/validation/validate.go
> +			serviceNamespace := helpers.FindServiceNamespace(api, nil)
`nilpointer dereference` is most likely not possible to occur, but I would handle it just to be  100% sure

2022-09-27 12:23 UTC, barchw commented on internal/validation/validate.go
> +					serviceNamespace := helpers.FindServiceNamespace(api, &r)
> `nilpointer dereference` is most likely not possible to occur, but I would handle it just to be 100% sure

Same here

2022-09-28 06:04 UTC, barchw approved these changes

2022-09-28 06:04 UTC, merged