Fetching workload label selector from service on cluster directly
kyma-project/api-gateway pull request #338
Opened 2023-05-02 15:18 UTC by videlov

**Description**

Changes proposed in this pull request:

- Fetching workload label selector from service on cluster directly

**Related issue(s)**

https://github.com/kyma-project/api-gateway/issues/278

2023-05-04 12:04 UTC, videlov commented
> Do you think that adding a integration scenario for this makes sense?

yes ofc, why not? generally if it is possible to test something that has specifics while running on a real cluster with integration test I would do it. Even thought, I would also make sure that calling endpoint works as well, which I did not test. Perhaps I should extend the test.

2023-05-04 13:13 UTC, barchw requested changes
The label selector needs to be applied both to Authorization Policy and Request Authentication

2023-05-05 06:51 UTC, barchw requested changes

2023-05-05 06:51 UTC, barchw commented on tests/integration/features/istio-jwt/istio_jwt.feature
> +    And CustomLabelSelector: Calling the "/ip" endpoint with a valid "JWT" token should result in status between 200 and 299
Helloworld app doesn't have /ip endpoint
```suggestion
    And CustomLabelSelector: There is an endpoint secured with JWT on path "/hello"
    When CustomLabelSelector: The APIRule is applied
    Then CustomLabelSelector: Calling the "/hello" endpoint without a token should result in status between 400 and 403
    And CustomLabelSelector: Calling the "/hello" endpoint with a valid "JWT" token should result in status between 200 and 299
```

2023-05-05 08:18 UTC, videlov commented
/test pull-api-gateway-integration-test

2023-05-05 08:35 UTC, barchw requested changes
Looks good either than the small linting issue, can be merged after we figure out how to propagate RBAC without updating Kyma resources

2023-05-05 08:35 UTC, barchw commented on internal/processing/istio/authorization_policy_processor.go
> +	serviceSelectorLabel string = "service"
Both of those new variables are unused
```suggestion
```

2023-05-05 09:21 UTC, videlov commented
/test pull-api-gateway-integration-test

2023-05-05 11:14 UTC, barchw approved these changes

2023-05-05 11:14 UTC, merged