Allow configuring CORS on APIRule
kyma-project/api-gateway pull request #760
Opened 2023-12-06 08:29 UTC by barchw

**Description**

Changes proposed in this pull request:

- ...
- ...
- ...

**Related issue(s)**

2023-12-06 08:29 UTC, barchw commented
/test all

2023-12-06 08:31 UTC, barchw commented
/test all

2023-12-06 11:35 UTC, barchw commented
/test all

2023-12-06 11:42 UTC, barchw commented
/test all

2023-12-07 08:33 UTC, barchw commented
/test all

2023-12-14 12:32 UTC, videlov requested changes

2023-12-14 12:32 UTC, videlov commented on tests/ui/tests/scripts/k3d-ci-kyma-dashboard-integration.sh
> +kubectl create ns kyma-system
`make create-namespace` instead evtl?

2023-12-15 08:15 UTC, barchw commented on apis/gateway/v1beta1/apirule_types.go
> +	AllowOrigins     []string `json:"allowOrigins,omitempty"`
This is because of the issue that `headers` part does not support `StringMatch`, that `allowOrigin` in VirtualService corsPolicy supported.

2023-12-15 09:08 UTC, videlov commented on apis/gateway/v1beta1/apirule_types.go
> +	AllowOrigins     []string `json:"allowOrigins,omitempty"`
Can you update the `04-40-cors-policy-design.md` doc as well then?

2023-12-18 09:43 UTC, barchw commented on apis/gateway/v1beta1/apirule_types.go
> +	AllowOrigins     []string `json:"allowOrigins,omitempty"`
I updated the CRD to use StringMatch instead, as in Istio

2023-12-19 08:50 UTC, videlov approved these changes

2023-12-19 11:39 UTC, nataliasitko commented on docs/release-notes/2.1.0.md
> +- Allow configuring CORS with the use of APIRule - https://github.com/kyma-project/api-gateway/pull/760
```suggestion
- You can now configure CORS with the use of APIRule. For more information, see the (PR)[https://github.com/kyma-project/api-gateway/pull/760].
```

2023-12-19 12:24 UTC, nataliasitko commented on docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
> +| **corsPolicy**                  |  **NO**   | CorsPolicy allows configuration of CORS headers send with the response. If `corsPolicy` is not defined, the default values are applied. If CorsPolicy i
```suggestion
| **corsPolicy**                  |  **NO**   | Allows configuring CORS headers sent with the response. If **corsPolicy** is not defined, the default values are applied. If **corsPolicy** is configured, only the CORS headers defined in the APIRule are sent with the response. For more information, see the [decision record](https://github.com/kyma-project/api-gateway/issues/752). |
```

2023-12-19 12:24 UTC, nataliasitko commented on docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
> +| **corsPolicy.allowHeaders**     |  **NO**   | Specifies headers allowed with `Access-Control-Allow-Headers` CORS header.
```suggestion
| **corsPolicy.allowHeaders**     |  **NO**   | Specifies headers allowed with the **Access-Control-Allow-Headers** CORS header.                                                                                                                                                                                                                                                                              |
```

2023-12-19 12:24 UTC, nataliasitko commented on docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
> +| **corsPolicy.allowMethods**     |  **NO**   | Specifies methods allowed with `Access-Control-Allow-Methods` CORS header.
```suggestion
| **corsPolicy.allowMethods**     |  **NO**   | Specifies methods allowed with the **Access-Control-Allow-Methods** CORS header.                                                                                                                                                                                                                                                                              |
```

2023-12-19 12:24 UTC, nataliasitko commented on docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
> +| **corsPolicy.allowOrigins**     |  **NO**   | Specifies origins allowed with `Access-Control-Allow-Origins` CORS header.
```suggestion
| **corsPolicy.allowOrigins**     |  **NO**   | Specifies origins allowed with the **Access-Control-Allow-Origins** CORS header.                                                                                                                                                                                                                                                                              |
```

2023-12-19 12:24 UTC, nataliasitko commented on docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
> +| **corsPolicy.allowCredentials** |  **NO**   | Specifies whether credentials are allowed in `Access-Control-Allow-Credentials` CORS header.
```suggestion
| **corsPolicy.allowCredentials** |  **NO**   | Specifies whether credentials are allowed in the **Access-Control-Allow-Credentials** CORS header.                                                                                                                                                                                                                                                            |
```

2023-12-19 12:24 UTC, nataliasitko commented on docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
> +| **corsPolicy.exposeHeaders**    |  **NO**   | Specifies headers exposed with `Access-Control-Expose-Headers` CORS header.
```suggestion
| **corsPolicy.exposeHeaders**    |  **NO**   | Specifies headers exposed with the **Access-Control-Expose-Headers** CORS header.                                                                                                                                                                                                                                                                             |
```

2023-12-19 12:24 UTC, nataliasitko commented on docs/user/custom-resources/apirule/04-10-apirule-custom-resource.md
> +| **corsPolicy.maxAge**           |  **NO**   | Specifies CORS policy cache maximum age, provided in `Access-Control-Max-Age` CORS header.
```suggestion
| **corsPolicy.maxAge**           |  **NO**   | Specifies the maximum age of CORS policy cache. The value is provided in the **Access-Control-Max-Age** CORS header.                                                                                                                                                                                                                                                              |
```

2023-12-19 12:39 UTC, nataliasitko approved these changes

2023-12-19 12:58 UTC, merged