Remove `generated-objects-labels` parameter
kyma-project/api-gateway pull request #880
Opened 2024-02-15 13:13 UTC by Ressetkk

/area ci
/kind cleanup
/cc @triffer 

This parameter is not used anymore, so it is safe to remove it

#490

2024-02-16 10:43 UTC, triffer requested changes
We should also remove the now unused field from [ApiRuleReconcilerConfiguration ](https://github.com/triffer/api-gateway/blob/0eea47ecb983f0c1ffcbc076054b7c24ac6579b4/controllers/gateway/types.go#L31-L31), [ReconciliationConfig](https://github.com/triffer/api-gateway/blob/0eea47ecb983f0c1ffcbc076054b7c24ac6579b4/internal/processing/types.go#L65) and all its occurrences down to the [processors](https://github.com/triffer/api-gateway/blob/0eea47ecb983f0c1ffcbc076054b7c24ac6579b4/internal/processing/istio/access_rule_processor.go#L14-L14) and tests.

2024-02-19 08:11 UTC, triffer submitted a review, later dismissed

2024-02-19 09:03 UTC, nataliasitko commented on docs/release-notes/2.2.0.md
> +- Removed `--generated-objects-labels` parameter and all the code that was used by it.
```suggestion
- Remove the **--generated-objects-labels** parameter and all the code that it used.
```

2024-02-19 10:02 UTC, nataliasitko approved these changes

2024-02-19 10:02 UTC, merged